# Umfpack lib usually requires linking to a blas library.
# It is up to the user of this module to find a BLAS and link to it.


#set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH TRUE)
if (UMFPACK_INCLUDES AND UMFPACK_LIBRARIES)
  set(UMFPACK_FIND_QUIETLY TRUE)
endif (UMFPACK_INCLUDES AND UMFPACK_LIBRARIES)

if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  set(CMAKE_FIND_LIBRARY_SUFFIXES ".a" ".dylib" ".so")
else()
  set(CMAKE_FIND_LIBRARY_SUFFIXES ".a" ".so")
endif()

find_path(UMFPACK_INCLUDES
  NAMES umfpack.h
  PATHS
  ENV CPATH
  ENV UMFPACKDIR
  $ENV{UMFPACKDIR}
  $ENV{UMFPACKDIR}/Include
  $ENV{UMFPACKDIR}/include
  ${INCLUDE_INSTALL_DIR}
  PATH_SUFFIXES
  suitesparse
  ufsparse
  Include
  include
)


find_library(UMFPACK_LIBRARIES umfpack PATHS ENV LIBRARY_PATH UMFPACKDIR $ENV{UMFPACKDIR} $ENV{UMFPACKDIR}/Lib ${LIB_INSTALL_DIR} PATH_SUFFIXES lib)
if(UMFPACK_LIBRARIES)

  if(NOT UMFPACK_LIBDIR)
	  get_filename_component(UMFPACK_LIBDIR ${UMFPACK_LIBRARIES} PATH)
	  #get_filename_component(UMFPACK_LIBDIR ${UMFPACK_LIBRARIES} REALPATH)
  endif(NOT UMFPACK_LIBDIR)

  find_library(CHOLMOD_LIBRARY cholmod PATHS ${UMFPACK_LIBDIR} $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})
  if(CHOLMOD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${CHOLMOD_LIBRARY})
  endif()

  find_library(SUITESPARSE_LIBRARY NAMES SuiteSparse suitesparse suitesparseconfig PATHS ${UMFPACK_LIBDIR} $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})
  if(SUITESPARSE_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${SUITESPARSE_LIBRARY})
  endif ()
  
  find_library(COLAMD_LIBRARY colamd PATHS ${UMFPACK_LIBDIR} $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})
  if(COLAMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${COLAMD_LIBRARY})
  endif ()

  find_library(CCOLAMD_LIBRARY ccolamd PATHS ${UMFPACK_LIBDIR} $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})  ## RD ajout
  if(COLAMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${CCOLAMD_LIBRARY})
  endif ()  
  
  find_library(AMD_LIBRARY amd PATHS ${UMFPACK_LIBDIR} $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})
  if(AMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${AMD_LIBRARY})
  endif ()

  find_library(CAMD_LIBRARY camd PATHS ${UMFPACK_LIBDIR} $ENV{UMFPACKDIR} ${LIB_INSTALL_DIR})  ## RD ajout
  if(AMD_LIBRARY)
    set(UMFPACK_LIBRARIES ${UMFPACK_LIBRARIES} ${CAMD_LIBRARY})
  endif ()

endif(UMFPACK_LIBRARIES)

set(UMFPACK_INCS ${UMFPACK_INCLUDES})
set(UMFPACK_LIBS ${UMFPACK_LIBDIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Umfpack DEFAULT_MSG
                                  UMFPACK_INCLUDES UMFPACK_LIBRARIES)

mark_as_advanced(UMFPACK_INCLUDES UMFPACK_LIBRARIES AMD_LIBRARY COLAMD_LIBRARY CHOLMOD_LIBRARY SUITESPARSE_LIBRARY UMFPACK_INCS UMFPACK_LIBS)
